DbConf:
  DSNTemplate: "%s:%s@tcp(%s:%s)/%s?timeout=%s&readTimeout=%s&writeTimeout=%s&parseTime=True&interpolateParams=True&loc=Local&autocommit=true"
  Username: ""
  Password: ""
  DBName: ""
  Hostname: ""
  Port: ""
  ConsulName: ""
  Timeout: "5500ms"
  ReadTimeout: "1s"
  WriteTimeout: "2s"
  MaxIdle: 100
  MaxOpen: 1000
